### ISSUE TITLE
Accetti PR?

### ISSUE THREAD

**Issue by DVDAndroid** [stefanodecillis/CoverIT#1]
Ciao, ho visto l'app e vorrei contribuire a migliorarne il design. Accetti PR?

**Comment by stefanodecillis** [comment]
Ciao!

Non so bene cosa sia un pr però se vuoi contribuire a migliorare l'app,
sicuramente c'è posto!
Ci tengo però a dire che questa è la mia prima applicazione Android e
quindi sarebbe un "lavoro" (se così vogliamo chiamarlo) no profit.
Se sei interessato, mi farebbe molto piacere:)




On 14 Nov 2017 14:28, "DVDAndroid" <notifications@github.com> wrote:

Ciao, ho visto l'app e vorrei contribuire a migliorarne il design. Accetti
PR?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/stefanodecillis/CoverIT/issues/1>, or mute the thread

**Comment by DVDAndroid** [comment]
PR = pull request

Faccio qualche modifica al mio fork e poi ti invio dei risultati 👍

**Comment by stefanodecillis** [comment]
Grande!
Comunque se vuoi, puoi contattarmi sulla mia mail
stefanodecillis96@gmail.com così da non passare per github :)
